name: Manual Task Reminder Workflow

on:
  workflow_dispatch:

jobs:
  send-reminder:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Run Task Reminder Script
      env:
        EMAIL_REMETENTE: ${{ secrets.EMAIL_REMETENTE }}
        EMAIL_DESTINATARIO: ${{ secrets.EMAIL_DESTINATARIO }}
        SENHA: ${{ secrets.SENHA }}
      run: python ./src/task_reminder.py
